[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = []

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
exclude = ["tests/"]

[[tool.mypy.overrides]]
module = [
    "flask.*",
    "celery.*",
    "prometheus_client.*",
    "redis.*",
    "werkzeug.*",
    "dotenv.*",
    "flask_sqlalchemy.*"
]
ignore_missing_imports = true
